using Inventory.Entity;
using Microsoft.EntityFrameworkCore;

namespace Inventory.EntityFrameworkCore.Seeds
{
    public static partial class Seed
    {
        private static void SeedCountry(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Country>(e =>
                {
                    e.HasData(
                        new Country {CountryId = 1, Name = "Austria"},
                        new Country {CountryId = 2, Name = "Bélgica"},
                        new Country {CountryId = 3, Name = "Bulgaria"},
                        new Country {CountryId = 4, Name = "Chipre"},
                        new Country {CountryId = 5, Name = "Dinamarca"},
                        new Country {CountryId = 6, Name = "España"},
                        new Country {CountryId = 7, Name = "Finlandia"},
                        new Country {CountryId = 8, Name = "Francia"},
                        new Country {CountryId = 9, Name = "Grecia"},
                        new Country {CountryId = 10, Name = "Hungría"},
                        new Country {CountryId = 11, Name = "Irlanda"},
                        new Country {CountryId = 12, Name = "Italia"},
                        new Country {CountryId = 13, Name = "Luxemburgo"},
                        new Country {CountryId = 14, Name = "Malta"},
                        new Country {CountryId = 15, Name = "Países Bajos"},
                        new Country {CountryId = 16, Name = "Polonia"},
                        new Country {CountryId = 17, Name = "Portugal"},
                        new Country {CountryId = 18, Name = "Reino Unido"},
                        new Country {CountryId = 19, Name = "Alemania"},
                        new Country {CountryId = 20, Name = "Rumanía"},
                        new Country {CountryId = 21, Name = "Suecia"},
                        new Country {CountryId = 22, Name = "Letonia"},
                        new Country {CountryId = 23, Name = "Estonia"},
                        new Country {CountryId = 24, Name = "Lituania"},
                        new Country {CountryId = 25, Name = "República Checa"},
                        new Country {CountryId = 26, Name = "República Eslovaca"},
                        new Country {CountryId = 27, Name = "Croacia"},
                        new Country {CountryId = 28, Name = "Eslovenia"},
                        new Country {CountryId = 29, Name = "Albania"},
                        new Country {CountryId = 30, Name = "Islandia"},
                        new Country {CountryId = 31, Name = "Liechtenstein"},
                        new Country {CountryId = 32, Name = "Mónaco"},
                        new Country {CountryId = 33, Name = "Noruega"},
                        new Country {CountryId = 34, Name = "Andorra"},
                        new Country {CountryId = 35, Name = "San Marino"},
                        new Country {CountryId = 36, Name = "Santa Sede"},
                        new Country {CountryId = 37, Name = "Suiza"},
                        new Country {CountryId = 38, Name = "Ucrania"},
                        new Country {CountryId = 39, Name = "Moldavia"},
                        new Country {CountryId = 40, Name = "Belarús"},
                        new Country {CountryId = 41, Name = "Georgia"},
                        new Country {CountryId = 42, Name = "Bosnia y Herzegovina"},
                        new Country {CountryId = 43, Name = "Armenia"},
                        new Country {CountryId = 44, Name = "Rusia"},
                        new Country {CountryId = 45, Name = "Macedonia"},
                        new Country {CountryId = 46, Name = "Serbia"},
                        new Country {CountryId = 47, Name = "Montenegro"},
                        new Country {CountryId = 48, Name = "Otros países de Europa"},
                        new Country {CountryId = 49, Name = "Burkina Faso"},
                        new Country {CountryId = 50, Name = "Angola"},
                        new Country {CountryId = 51, Name = "Argelia"},
                        new Country {CountryId = 52, Name = "Benin"},
                        new Country {CountryId = 53, Name = "Botswana"},
                        new Country {CountryId = 54, Name = "Burundi"},
                        new Country {CountryId = 55, Name = "Cabo Verde"},
                        new Country {CountryId = 56, Name = "Camerún"},
                        new Country {CountryId = 57, Name = "Comores"},
                        new Country {CountryId = 58, Name = "Congo"},
                        new Country {CountryId = 59, Name = "Costa de Marfil"},
                        new Country {CountryId = 60, Name = "Djibouti"},
                        new Country {CountryId = 61, Name = "Egipto"},
                        new Country {CountryId = 62, Name = "Etiopía"},
                        new Country {CountryId = 63, Name = "Gabón"},
                        new Country {CountryId = 64, Name = "Gambia"},
                        new Country {CountryId = 65, Name = "Ghana"},
                        new Country {CountryId = 66, Name = "Guinea"},
                        new Country {CountryId = 67, Name = "Guinea-Bissau"},
                        new Country {CountryId = 68, Name = "Guinea Ecuatorial"},
                        new Country {CountryId = 69, Name = "Kenia"},
                        new Country {CountryId = 70, Name = "Lesotho"},
                        new Country {CountryId = 71, Name = "Liberia"},
                        new Country {CountryId = 72, Name = "Libia"},
                        new Country {CountryId = 73, Name = "Madagascar"},
                        new Country {CountryId = 74, Name = "Malawi"},
                        new Country {CountryId = 75, Name = "Mali"},
                        new Country {CountryId = 76, Name = "Marruecos"},
                        new Country {CountryId = 77, Name = "Mauricio"},
                        new Country {CountryId = 78, Name = "Mauritania"},
                        new Country {CountryId = 79, Name = "Mozambique"},
                        new Country {CountryId = 80, Name = "Namibia"},
                        new Country {CountryId = 81, Name = "Níger"},
                        new Country {CountryId = 82, Name = "Nigeria"},
                        new Country {CountryId = 83, Name = "República Centroafricana"},
                        new Country {CountryId = 84, Name = "Sudáfrica"},
                        new Country {CountryId = 85, Name = "Ruanda"},
                        new Country {CountryId = 86, Name = "Santo Tomé y Príncipe"},
                        new Country {CountryId = 87, Name = "Senegal"},
                        new Country {CountryId = 88, Name = "Seychelles"},
                        new Country {CountryId = 89, Name = "Sierra Leona"},
                        new Country {CountryId = 90, Name = "Somalia"},
                        new Country {CountryId = 91, Name = "Sudán"},
                        new Country {CountryId = 92, Name = "Swazilandia"},
                        new Country {CountryId = 93, Name = "Tanzania"},
                        new Country {CountryId = 94, Name = "Chad"},
                        new Country {CountryId = 95, Name = "Togo"},
                        new Country {CountryId = 96, Name = "Túnez"},
                        new Country {CountryId = 97, Name = "Uganda"},
                        new Country {CountryId = 98, Name = "República Democrática del Congo"},
                        new Country {CountryId = 99, Name = "Zambia"},
                        new Country {CountryId = 100, Name = "Zimbabwe"},
                        new Country {CountryId = 101, Name = "Eritrea"},
                        new Country {CountryId = 102, Name = "Sudán del Sur"},
                        new Country {CountryId = 103, Name = "Otros países de África"},
                        new Country {CountryId = 104, Name = "Canadá"},
                        new Country {CountryId = 105, Name = "Estados Unidos de América"},
                        new Country {CountryId = 106, Name = "México"},
                        new Country {CountryId = 107, Name = "Antigua y Barbuda"},
                        new Country {CountryId = 108, Name = "Bahamas"},
                        new Country {CountryId = 109, Name = "Barbados"},
                        new Country {CountryId = 110, Name = "Belice"},
                        new Country {CountryId = 111, Name = "Costa Rica"},
                        new Country {CountryId = 112, Name = "Cuba"},
                        new Country {CountryId = 113, Name = "Dominica"},
                        new Country {CountryId = 114, Name = "El Salvador"},
                        new Country {CountryId = 115, Name = "Granada"},
                        new Country {CountryId = 116, Name = "Guatemala"},
                        new Country {CountryId = 117, Name = "Haití"},
                        new Country {CountryId = 118, Name = "Honduras"},
                        new Country {CountryId = 119, Name = "Jamaica"},
                        new Country {CountryId = 120, Name = "Nicaragua"},
                        new Country {CountryId = 121, Name = "Panamá"},
                        new Country {CountryId = 122, Name = "San Vicente y las Granadinas"},
                        new Country
                        {
                            CountryId = Country.REPUBLICA_DOMINICANA,
                            Name = "República Dominicana"
                        },
                        new Country {CountryId = 124, Name = "Trinidad y Tobago"},
                        new Country {CountryId = 125, Name = "Santa Lucía"},
                        new Country {CountryId = 126, Name = "San Cristóbal y Nieves"},
                        new Country {CountryId = 127, Name = "Argentina"},
                        new Country {CountryId = 128, Name = "Bolivia"},
                        new Country {CountryId = 129, Name = "Brasil"},
                        new Country {CountryId = 130, Name = "Colombia"},
                        new Country {CountryId = 131, Name = "Chile"},
                        new Country {CountryId = 132, Name = "Ecuador"},
                        new Country {CountryId = 133, Name = "Guyana"},
                        new Country {CountryId = 134, Name = "Paraguay"},
                        new Country {CountryId = 135, Name = "Perú"},
                        new Country {CountryId = 136, Name = "Surinam"},
                        new Country {CountryId = 137, Name = "Uruguay"},
                        new Country {CountryId = 138, Name = "Venezuela"},
                        new Country {CountryId = 139, Name = "Otros países de América"},
                        new Country {CountryId = 140, Name = "Afganistán"},
                        new Country {CountryId = 141, Name = "Arabia Saudí"},
                        new Country {CountryId = 142, Name = "Bahréin"},
                        new Country {CountryId = 143, Name = "Bangladesh"},
                        new Country {CountryId = 144, Name = "Myanmar"},
                        new Country {CountryId = 145, Name = "China"},
                        new Country {CountryId = 146, Name = "Emiratos Árabes Unidos"},
                        new Country {CountryId = 147, Name = "Filipinas"},
                        new Country {CountryId = 148, Name = "India"},
                        new Country {CountryId = 149, Name = "Indonesia"},
                        new Country {CountryId = 150, Name = "Iraq"},
                        new Country {CountryId = 151, Name = "Irán"},
                        new Country {CountryId = 152, Name = "Israel"},
                        new Country {CountryId = 153, Name = "Japón"},
                        new Country {CountryId = 154, Name = "Jordania"},
                        new Country {CountryId = 155, Name = "Camboya"},
                        new Country {CountryId = 156, Name = "Kuwait"},
                        new Country {CountryId = 157, Name = "Laos"},
                        new Country {CountryId = 158, Name = "Líbano"},
                        new Country {CountryId = 159, Name = "Malasia"},
                        new Country {CountryId = 160, Name = "Maldivas"},
                        new Country {CountryId = 161, Name = "Mongolia"},
                        new Country {CountryId = 162, Name = "Nepal"},
                        new Country {CountryId = 163, Name = "Omán"},
                        new Country {CountryId = 164, Name = "Pakistán"},
                        new Country {CountryId = 165, Name = "Qatar"},
                        new Country {CountryId = 166, Name = "Corea"},
                        new Country {CountryId = 167, Name = "Corea del Norte"},
                        new Country {CountryId = 168, Name = "Singapur"},
                        new Country {CountryId = 169, Name = "Siria"},
                        new Country {CountryId = 170, Name = "Sri Lanka"},
                        new Country {CountryId = 171, Name = "Tailandia"},
                        new Country {CountryId = 172, Name = "Turquía"},
                        new Country {CountryId = 173, Name = "Vietnam"},
                        new Country {CountryId = 174, Name = "Brunei"},
                        new Country {CountryId = 175, Name = "Islas Marshall"},
                        new Country {CountryId = 176, Name = "Yemen"},
                        new Country {CountryId = 177, Name = "Azerbaiyán"},
                        new Country {CountryId = 178, Name = "Kazajstán"},
                        new Country {CountryId = 179, Name = "Kirguistán"},
                        new Country {CountryId = 180, Name = "Tayikistán"},
                        new Country {CountryId = 181, Name = "Turkmenistán"},
                        new Country {CountryId = 182, Name = "Uzbekistán"},
                        new Country {CountryId = 183, Name = "Bhután"},
                        new Country
                        {
                            CountryId = 184,
                            Name = "Palestina. Estado Observador, no miembro de Naciones Unidas"
                        },
                        new Country {CountryId = 185, Name = "Otros países de Asia"},
                        new Country {CountryId = 186, Name = "Australia"},
                        new Country {CountryId = 187, Name = "Fiji"},
                        new Country {CountryId = 188, Name = "Nueva Zelanda"},
                        new Country {CountryId = 189, Name = "Papúa Nueva Guinea"},
                        new Country {CountryId = 190, Name = "Islas Salomón"},
                        new Country {CountryId = 191, Name = "Samoa"},
                        new Country {CountryId = 192, Name = "Tonga"},
                        new Country {CountryId = 193, Name = "Vanuatu"},
                        new Country {CountryId = 194, Name = "Micronesia"},
                        new Country {CountryId = 195, Name = "Tuvalu"},
                        new Country {CountryId = 196, Name = "Islas Cook"},
                        new Country {CountryId = 197, Name = "Kiribati"},
                        new Country {CountryId = 198, Name = "Nauru"},
                        new Country {CountryId = 199, Name = "Palaos"},
                        new Country {CountryId = 200, Name = "Timor Oriental"},
                        new Country {CountryId = 201, Name = "Otros países de Oceanía"}
                    );
                }
            );
        }
    }
}